---
title = "Внезапно поучаствовал в коллективном иске в США"
tags = ["practice", "business", "state"]
published_at = "2024-08-31T12:00:00+00:00"
seo_description = "Короткая история как меня вписали в коллективный иск и что из этого вышло."
seo_image = ""
---

Неожиданно столкнулся с работающим правосудием в США, причём почти ничего не делал для этого.

- Году в 2017-2018, когда был бум крипты, подписался в один майнерский стартап: купил их токенов, одну единицу оборудования.
- Стартап пошёл в рост, начал строить мега ферму, но не фортануло — на пик их трат пришлось падение биткоина, деньги кончились, контора обанкротилась. Забавно, что через месяц-два после подачи на банкротство биткоин всё отыграл назад. Не повезло :-)
- На потерянные деньги тогда уже забил, конечно. Действовал по правилу «вкладывай только 10% дохода, которые не жалко потерять».
- Поскольку юридически всё происходило в США, народ там собрался и подал коллективный иск.
- Мне прислали письмо, по которому я автоматически среди истцов, если не откажусь. Я не отказался, интересно же.
- Всё затихло до этого (2024) года.
- Весной пришло ещё одно письмо: «подтвердите владение токенами и укажите их количество, мы победили и поделим оставшееся на всех владельцев пропорционально, за вычитом здоровой комиссии юристам».
- А как я подтвержу? Больше 5 лет прошло. Счёт в банке РБ закрыт, админка конторы недоступна, прямой транзакции в блокчейне нет — отправлял прямо с какой-то биржи (хотя так делать не рекомендуется).
- Нашёл на почте письмо от конторы о том, что я купил токены (без указания количества), распечатал в pdf. Прикрепил к заявке его и скриншоты транзакции с биржи за тот период. Дал адрес своего текущего кошелька, где эти токены лежат мёртвым грузом. Отправил.
- Сегодня на банковский счёт прислали 700$. Это, конечно, не всё потерянное, но процентов 25% будет, может даже больше.

Какие выводы можно из этого сделать:

- Иногда вашему бизнесу может просто не фортануть.
- Сохраняйте всю электронную почту, никогда не узнаете что и когда пригодится.
- Коллективные иски работают и делают это интересным образом.
- Правосудие в США работает долго, но, видимо, неотвратимо и неожиданно лояльно к левым минорным участникам конфликта. По крайней мере иногда.
